sonar.projectKey=ibivibe-hub_ibivibe
sonar.organization=ibivibe-hub
sonar.projectName=ibivibe
sonar.projectVersion=1.0.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  android/**,\
  ios/**,\
  linux/**,\
  macos/**,\
  windows/**,\
  build/**,\
  .dart_tool/**,\
  assets/**,\
  **/*.iml,\
  **/*.g.dart,\
  lib/generated_plugin_registrant.dart

sonar.coverage.exclusions=\
  lib/main.dart,\
  lib/generated_plugin_registrant.dart,\
  **/*.g.dart,\
  **/*.freezed.dart,\
  lib/app/router/**,\
  lib/app/theme/**

sonar.dart.analysis.reportPaths=.dart_tool/flutter_analyzer_bundle.txt
sonar.flutter.coverage.reportPath=coverage/lcov.info